sudo: false
dist: xenial

services:
  - postgresql
  - mysql
  - docker
os:
  - linux
language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

sudo: required

before_install:
  - sudo apt install unixodbc-dev
  # 启动sqlserver docker容器
  - docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=django321!' -p 1433:1433 -d mcr.microsoft.com/mssql/server:2017-latest

install:
  - pip install tox-travis coveralls

before_script:
  - psql -c 'create database test;' -U postgres
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

script:
  - tox

after_success:
  - coveralls