sudo: false
dist: xenial

services:
  - postgresql
  - mysql
os:
  - linux
language: python
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36

    - python: 3.6
      env: TOXENV=py37

python:
  - "3.6"
  - "3.7"


install:
  - pip install tox

before_script:
  - psql -c 'create database test;' -U postgres
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

script:
  - tox

